# MongoDB Local Connection
spring.data.mongodb.uri=mongodb://localhost:27017/smartstudy_db
spring.data.mongodb.database=smartstudy_db

jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000

# Gemini API
gemini.api.key=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
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent

server.port=8081
ocr.api.key=K89111392788957

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB