# MongoDB Local Connection
spring.data.mongodb.uri=mongodb+srv://sapnakannaujiya347_db_user:1LfdeEOdUGzzfgUI@smartstudy-cluster.kerbzu2.mongodb.net/smartstudy_db?retryWrites=true&w=majority&appName=smartstudy-cluster
spring.data.mongodb.database=smartstudy_db

jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000

# Gemini API
gemini.api.key=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
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent

server.port=8081
ocr.api.key=K89111392788957

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

